// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Comment struct {
	ID        int64     `json:"id"`
	PostID    int64     `json:"post_id"`
	UserID    int64     `json:"user_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type CommentLike struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
}

type Conversation struct {
	ID               int64     `json:"id"`
	UserFirstID      int64     `json:"user_first_id"`
	UserSecondID     int64     `json:"user_second_id"`
	LastMsgCreatedAt time.Time `json:"last_msg_created_at"`
}

type Follower struct {
	UserFromID int64 `json:"user_from_id"`
	UserToID   int64 `json:"user_to_id"`
}

type Message struct {
	ID             int64     `json:"id"`
	ConversationID int64     `json:"conversation_id"`
	UserID         int64     `json:"user_id"`
	Text           string    `json:"text"`
	CreatedAt      time.Time `json:"created_at"`
}

type Post struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
}

type PostLike struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
}

type User struct {
	ID             int64  `json:"id"`
	Email          string `json:"email"`
	Fullname       string `json:"fullname"`
	HashedPassword string `json:"hashed_password"`
	Nickname       string `json:"nickname"`
	AvatarUrl      string `json:"avatar_url"`
}
