// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64     `json:"id"`
	PostID    int64     `json:"post_id"`
	UserID    int64     `json:"user_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type CommentLike struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
}

type Conversation struct {
	ID      int64 `json:"id"`
	User1ID int64 `json:"user1_id"`
	User2ID int64 `json:"user2_id"`
}

type Folower struct {
	UserFromID int64 `json:"user_from_id"`
	UserToID   int64 `json:"user_to_id"`
}

type Message struct {
	ID             int64     `json:"id"`
	ConversationID int64     `json:"conversation_id"`
	UserID         int64     `json:"user_id"`
	Text           string    `json:"text"`
	CreatedAt      time.Time `json:"created_at"`
}

type Post struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	CreatedAt   time.Time      `json:"created_at"`
}

type PostLike struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
}

type User struct {
	ID             int64          `json:"id"`
	Email          string         `json:"email"`
	Fullname       string         `json:"fullname"`
	HashedPassword string         `json:"hashed_password"`
	Nickname       string         `json:"nickname"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
}
