// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64
	PostID    int64
	UserID    int64
	Text      string
	CreatedAt time.Time
}

type CommentLike struct {
	CommentID int64
	UserID    int64
}

type Conversation struct {
	ID      int64
	User1ID int64
	User2ID int64
}

type Folower struct {
	UserFromID int64
	UserToID   int64
}

type Message struct {
	ID             int64
	ConversationID int64
	UserID         int64
	Text           string
	CreatedAt      time.Time
}

type Post struct {
	ID          int64
	UserID      int64
	Title       sql.NullString
	Description sql.NullString
	ImageUrl    sql.NullString
	CreatedAt   time.Time
}

type PostLike struct {
	PostID int64
	UserID int64
}

type User struct {
	ID             int64
	Email          string
	Fullname       string
	HashedPassword string
	Nickname       string
	AvatarUrl      sql.NullString
}
